[package]
name = "hues"
version = "0.1.0"
edition = "2021"

[profile.dev.package.ggez]
opt-level = 1

[dependencies]
ggez = "0.9.3"
quick-xml = { version = "0.31.0", features = ["serialize"] }
zip = "0.6.6"
serde = { version = "1.0.197", features = ["derive"] }